### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by ChenHongBo0420** [yfsong0709/EfficientGCNv1#4]
非常感谢您的卓越工作
拜读过您的论文，有一些疑问
1.您如何计算Flops shift-gcn的作者说可以用thop 貌似只是通用于CNN 而且我在您的代码中没有看到有关于flops计算的内容 您是手工计算的吗
2.我注意到您数据流较上一个版本增加了bn层和融合前预先处理 当我follow您的想法时 发现在我的模型中 验证准确率严重下滑 仅有个位数 
3.拜读过您论文5.5.3中 您谈到SGN使用帧转化将300帧转化为20帧 这个我一直持有疑问 感谢您的点出 我想问这两种方法有什么不同吗 还有flops 参数量会有变化吗
4.您提到 因为ntu60存在噪声 所以在手部的末端有一些难以区分 我注意到在其它的工作如SGN HCN CTR-GCN中都对NTU数据集进行了噪声的预处理 还有一些工作提到细粒的缺失 您对此怎么看

**Comment by yfsong0709** [comment]
@ChenHongBo0420 抱歉现在才回复，最近比较忙。非常感谢你对我工作的关注。对于你的几个问题，我的想法是这样的：
1. thop是用来计算FLOPs和#Param的。我不太清楚你说的torch.one指的是什么？
2. 经过最近的实验，我发现提前融合模型这个idea带来的是#Param上的减少，也不用跑好几个stream了，但在正确率上的提升并不明显。至于正确率大幅下降，可能的原因挺多的，需要具体分析。建议你多看看effgcn里融合前后的处理。
3. SGN把300帧转换成20帧，应该是用的抽帧的方式。这样的话一些时间上的细节肯定是会被忽略掉的，会影响模型正确率。但是只有20帧的话可以加速模型的temporal cnn，大幅降低temporal cnn里的FLOPs，不过参数量是不影响的。简单考虑一下，temporal cnn是在用一个长度为L的滑动窗来卷积300帧的序列，如果把300帧降低成20帧，滑不了几次就到头了，自然FLOPs会非常低的。而参数量是跟滑动窗的长度有关的，和序列长度无关，所以参数量是一样的。
4. 噪声预处理可以过滤掉一些干扰信息，让模型学到更有价值的信息。但这个不太好把握，也很有可能会过滤掉一些比较重要的信息，所以我暂时没有什么好的方法来准确地过滤掉噪声。
5. 我的batch size设置一般是16或者32，具体可见configs里的yaml文件，里面有详细的模型超参数设定。
