### ISSUE TITLE
是否对2D的骨骼数据也有效呢

### ISSUE THREAD

**Issue by weizh588** [yfsong0709/EfficientGCNv1#5]
非常感谢您的卓越工作,
想请问您的模型，是否对2D的骨骼数据也有效呢?

**Comment by yfsong0709** [comment]
@weizh588 有效的，只需要对应修改一下input数据和dataloader这一块就可以了。这个模型我用来参加过UAV-human的skeleton数据集，结果也不错，拿到了top-3，那个数据集就是2D的
