### ISSUE TITLE
OpenPose keypoint

### ISSUE THREAD

**Issue by cici203** [yfsong0709/EfficientGCNv1#6]
Instead of directly using the 3D keypoint coordinates provided by the dataset, is there any result of action recognition by using OpenPose via RGB to obtain key point coordinates?  That makes more sense.

**Comment by yfsong0709** [comment]
I have participated in competition on UAV-Human dataset (https://github.com/SUTDCV/UAV-Human), and won the 3rd place. It is easy to transform our model to fit 2D skeleton joints obtained by OpenPose.
